[ci] might be there?

diff --git a/.forgejo/workflows/argocd-diff.yaml b/.forgejo/workflows/argocd-diff.yaml
--- a/.forgejo/workflows/argocd-diff.yaml
+++ b/.forgejo/workflows/argocd-diff.yaml
@@ -38,10 +38,14 @@ jobs:
           echo "Starting ArgoCD diff process..."
 
           set +e
-          set -x
+
+          OUTPUT_DIR="artifacts"
+          mkdir -p $OUTPUT_DIR
 
           TEST_REPO=${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}
           REF_NAME=${FORGEJO_REF_NAME:-$FORGEJO_SHA}
+
+          ARGOCD_ERROR=0
 
           for app_file in argocd/applications/*.yaml; do
             [ -e "$app_file" ] || continue
@@ -51,6 +55,12 @@ jobs:
             argocd app get $APP_NAME --refresh \
                 --auth-token "$ARGOCD_TOKEN" \
                 --server "$ARGOCD_SERVER"
+
+            if [ $? -ne 0 ]; then
+              echo "ERROR: argocd cli was unable to refresh"
+              ARGOCD_ERROR=$?
+              continue
+            fi
 
             HAS_SOURCES=$(yq eval '.spec.sources | select(. != null)' "$app_file")
             if [ -z "$HAS_SOURCES" ]; then
@@ -75,16 +85,26 @@ jobs:
             argocd app diff "$APP_NAME" ${REV_FLAGS} \
               --server "$ARGOCD_SERVER" \
               --auth-token "$ARGOCD_TOKEN" \
-              --server-side-generate 
+              --server-side-generate  > ${OUTPUT_DIR}/"${APP_NAME}.diff" 2> ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"
 
-            EXIT_CODE=$?
-
-            if [ $EXIT_CODE -eq 0 ]; then
-              echo "✅ No differences found for $APP_NAME."
-            elif [ $EXIT_CODE -eq 1 ]; then
-              echo "⚠️ Differences found for $APP_NAME. (Pipeline continuing)"
-            else
-              echo "❌ FATAL: ArgoCD command failed with exit code $EXIT_CODE."
+            if [ $? -eq 1 ]; then
+              echo "diff found in $APP_NAME -- running dryrun sync"
+              argocd app sync "$APP_NAME" ${REV_FLAGS} \
+                --server "$ARGOCD_SERVER" \
+                --auth-token "$ARGOCD_TOKEN" \
+                --server-side --dry-run  > ${OUTPUT_DIR}/"${APP_NAME}.sync" 2>&1
+            elif [ $? -ne 0 ]; then
+              echo "ERROR: argocd cli was unable to diff"
+              continue
             fi
               
           done
+
+          find "$OUTPUT_DIR" -type f -empty -delete
+
+      - name: Upload artifacts
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: argocd-application-diffs
+          path: artifacts/
