[ci] okay, we now include the app of apps

diff --git a/.forgejo/workflows/argocd-diff.yaml b/.forgejo/workflows/argocd-diff.yaml
--- a/.forgejo/workflows/argocd-diff.yaml
+++ b/.forgejo/workflows/argocd-diff.yaml
@@ -43,9 +43,44 @@ jobs:
           mkdir -p $OUTPUT_DIR
 
           TEST_REPO=${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}
-          REF_NAME=${FORGEJO_REF_NAME:-$FORGEJO_SHA}
+          REF_NAME=${FORGEJO_REF_NAME}
+
+          if [ "${REF_NAME}" == "" ]; then
+            REF_NAME=${FORGEJO_SHA}
+          fi
 
           ARGOCD_ERROR=0
+
+          APP_NAME=applications-raft
+          argocd app get $APP_NAME --refresh \
+            --auth-token "$ARGOCD_TOKEN" \
+            --server "$ARGOCD_SERVER" > /dev/null 2> $OUTPUT_DIR/"${APP_NAME}_refresh.stderr"
+
+          argocd app diff "$APP_NAME" ${REV_FLAGS} \
+            --server "$ARGOCD_SERVER" \
+            --auth-token "$ARGOCD_TOKEN" \
+            --server-side-generate  > ${OUTPUT_DIR}/"${APP_NAME}.diff" 2> ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"
+
+          if [ $? -eq 1 ]; then
+            echo "diff found in $APP_NAME"
+
+            cat ${OUTPUT_DIR}/"${APP_NAME}.diff"
+
+            argocd app sync "$APP_NAME" ${REV_FLAGS} \
+              --server "$ARGOCD_SERVER" \
+              --auth-token "$ARGOCD_TOKEN" \
+              --server-side --dry-run  > ${OUTPUT_DIR}/"${APP_NAME}.sync" 2>&1
+          elif [ $? -gt 1 ]; then
+            echo "ERROR: argocd cli was unable to diff exit code $?"
+            echo ""
+            echo "stdout:"
+            cat ${OUTPUT_DIR}/"${APP_NAME}.diff"
+            echo ""
+            echo "stderr:"
+            cat ${OUTPUT_DIR}/"${APP_NAME}.stderr"
+            ARGOCD_ERROR=$?
+            continue
+          fi
 
           for app_file in argocd/applications/*.yaml; do
             [ -e "$app_file" ] || continue
